package com.appdynamics.extensions.snmp;


public enum EventTypeEnum {

    POLICY_OPEN_WARNING,
    POLICY_OPEN_CRITICAL,
    POLICY_CLOSE_WARNING,
    POLICY_CLOSE_CRITICAL,
    POLICY_UPGRADED,
    POLICY_DOWNGRADED,
    POLICY_CANCELED_WARNING,
    POLICY_CANCELED_CRITICAL,
    POLICY_CONTINUES_CRITICAL,
    POLICY_CONTINUES_WARNING,
    POLICY_CANCELED,
    POLICY_CLOSE
}
